/*
Created: 6/19/2018
Modified: 6/19/2018
Model: PostgreSQL 10
Database: PostgreSQL 10
*/


-- Create tables section -------------------------------------------------

-- Table CLIENT

CREATE TABLE "CLIENT"(
 "ID" Serial NOT NULL,
 "NAME" Character varying NOT NULL,
 "ADRESS" Character varying,
 "DATE_OF_BIRTH" Date NOT NULL,
 "CPF" Character varying NOT NULL,
 "EMAIL" Character varying,
 "PHONE" Bigint
)
;

-- Add keys for table CLIENT

ALTER TABLE "CLIENT" ADD CONSTRAINT "Key1" PRIMARY KEY ("ID")
;

-- Table MOVIE

CREATE TABLE "MOVIE"(
 "ID" Serial NOT NULL,
 "TITLE" Character varying NOT NULL,
 "RELEASE_DATE" Date NOT NULL,
 "RATING" Bigint,
 "POSTER" Path,
 "DIRECTOR_ID" Integer,
 "TOTAL_COPIES" Bigint,
 "AVAILABLE_COPIES" Bigint
)
;

-- Create indexes for table MOVIE

CREATE INDEX "IX_Relationship1" ON "MOVIE" ("DIRECTOR_ID")
;

-- Add keys for table MOVIE

ALTER TABLE "MOVIE" ADD CONSTRAINT "Key2" PRIMARY KEY ("ID")
;

-- Table ACTOR

CREATE TABLE "ACTOR"(
 "ID" Serial NOT NULL,
 "NAME" Character varying NOT NULL,
 "DATE_OF_BIRTH" Date NOT NULL,
 "DATE_OF_DEATH" Date,
 "NATIONALITY" Character varying
)
;

-- Add keys for table ACTOR

ALTER TABLE "ACTOR" ADD CONSTRAINT "Key3" PRIMARY KEY ("ID")
;

-- Table DIRECTOR

CREATE TABLE "DIRECTOR"(
 "ID" Serial NOT NULL,
 "NAME" Character varying NOT NULL,
 "DATE_OF_BIRTH" Date NOT NULL,
 "DATE_OF_DEATH" Date,
 "NATIONALITY" Character varying
)
;

-- Add keys for table DIRECTOR

ALTER TABLE "DIRECTOR" ADD CONSTRAINT "Key4" PRIMARY KEY ("ID")
;

-- Table PRIZES

CREATE TABLE "PRIZES"(
 "ID" Bigint NOT NULL,
 "NOMINATION" Bit varying NOT NULL,
 "EVENT" Character varying NOT NULL,
 "RECIEVED" Boolean,
 "ACTOR_MOVIE_ID" Integer
)
;

-- Create indexes for table PRIZES

CREATE INDEX "IX_Relationship15" ON "PRIZES" ("ACTOR_MOVIE_ID")
;

-- Add keys for table PRIZES

ALTER TABLE "PRIZES" ADD CONSTRAINT "Key5" PRIMARY KEY ("ID")
;

-- Table ACTOR_IN_MOVIE

CREATE TABLE "ACTOR_IN_MOVIE"(
 "ID" Serial NOT NULL,
 "ROLE" Character varying NOT NULL,
 "MOVIE_ID" Integer,
 "ACTOR_ID" Integer
)
;

-- Create indexes for table ACTOR_IN_MOVIE

CREATE INDEX "IX_Relationship12" ON "ACTOR_IN_MOVIE" ("MOVIE_ID")
;

CREATE INDEX "IX_Relationship13" ON "ACTOR_IN_MOVIE" ("ACTOR_ID")
;

-- Add keys for table ACTOR_IN_MOVIE

ALTER TABLE "ACTOR_IN_MOVIE" ADD CONSTRAINT "Key6" PRIMARY KEY ("ID")
;

-- Table RENTALS

CREATE TABLE "RENTALS"(
 "ID" Serial NOT NULL,
 "DATE_OF_RENTAL" Date NOT NULL,
 "DUE_DATE" Date NOT NULL,
 "DATE_OF_DELIVERY" Date,
 "CLIENT_ID" Integer,
 "STORE_ID" Integer,
 "MOVIE_ID" Integer
)
;

-- Create indexes for table RENTALS

CREATE INDEX "IX_Relationship16" ON "RENTALS" ("CLIENT_ID")
;

CREATE INDEX "IX_Relationship26" ON "RENTALS" ("STORE_ID","MOVIE_ID")
;

-- Add keys for table RENTALS

ALTER TABLE "RENTALS" ADD CONSTRAINT "Key7" PRIMARY KEY ("ID")
;

-- Table STORE

CREATE TABLE "STORE"(
 "ID" Serial NOT NULL,
 "ADRESS" Character varying NOT NULL,
 "PHONE" Character varying NOT NULL,
 "MANAGER_ID" Integer
)
;

-- Create indexes for table STORE

CREATE INDEX "IX_Relationship19" ON "STORE" ("MANAGER_ID")
;

-- Add keys for table STORE

ALTER TABLE "STORE" ADD CONSTRAINT "Key8" PRIMARY KEY ("ID")
;

-- Table EMPLOYEE

CREATE TABLE "EMPLOYEE"(
 "ID" Serial NOT NULL,
 "NAME" Character varying NOT NULL,
 "ADRESS" Character varying,
 "DATE_OF_BIRTH" Date NOT NULL,
 "CPF" Character varying NOT NULL,
 "EMAIL" Character varying,
 "PHONE" Bigint,
 "STORE_ID" Integer
)
;

-- Create indexes for table EMPLOYEE

CREATE INDEX "IX_Relationship18" ON "EMPLOYEE" ("STORE_ID")
;

-- Add keys for table EMPLOYEE

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "Key9" PRIMARY KEY ("ID")
;

-- Table COPIES

CREATE TABLE "COPIES"(
 "STORE_ID" Integer NOT NULL,
 "MOVIE_ID" Integer NOT NULL,
 "TOTAL" Bigint NOT NULL,
 "AVAILABLE" Bigint NOT NULL
)
;

-- Add keys for table COPIES

ALTER TABLE "COPIES" ADD CONSTRAINT "Key10" PRIMARY KEY ("STORE_ID","MOVIE_ID")
;
-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE "MOVIE" ADD CONSTRAINT "directs" FOREIGN KEY ("DIRECTOR_ID") REFERENCES "DIRECTOR" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "ACTOR_IN_MOVIE" ADD CONSTRAINT "played by" FOREIGN KEY ("MOVIE_ID") REFERENCES "MOVIE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "ACTOR_IN_MOVIE" ADD CONSTRAINT "acts" FOREIGN KEY ("ACTOR_ID") REFERENCES "ACTOR" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "PRIZES" ADD CONSTRAINT "nominates" FOREIGN KEY ("ACTOR_MOVIE_ID") REFERENCES "ACTOR_IN_MOVIE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "RENTALS" ADD CONSTRAINT "Relationship16" FOREIGN KEY ("CLIENT_ID") REFERENCES "CLIENT" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "Relationship18" FOREIGN KEY ("STORE_ID") REFERENCES "STORE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "STORE" ADD CONSTRAINT "Relationship19" FOREIGN KEY ("MANAGER_ID") REFERENCES "EMPLOYEE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "COPIES" ADD CONSTRAINT "Relationship24" FOREIGN KEY ("STORE_ID") REFERENCES "STORE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "COPIES" ADD CONSTRAINT "Relationship25" FOREIGN KEY ("MOVIE_ID") REFERENCES "MOVIE" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE "RENTALS" ADD CONSTRAINT "Relationship26" FOREIGN KEY ("STORE_ID", "MOVIE_ID") REFERENCES "COPIES" ("STORE_ID", "MOVIE_ID") ON DELETE NO ACTION ON UPDATE NO ACTION
;



